/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.autodesk.ws.avro;  
@SuppressWarnings("all")
public class Call extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Call\",\"namespace\":\"com.autodesk.ws.avro\",\"fields\":[{\"name\":\"responding_product_id\",\"type\":\"string\"},{\"name\":\"requesting_product_id\",\"type\":\"string\"},{\"name\":\"module\",\"type\":\"string\"},{\"name\":\"operation\",\"type\":[\"null\",\"string\"]},{\"name\":\"suboperation\",\"type\":[\"null\",\"string\"]},{\"name\":\"target_object_uri\",\"type\":[\"null\",\"string\"]},{\"name\":\"object_size\",\"type\":[\"null\",\"long\"]},{\"name\":\"execution_time\",\"type\":[\"null\",\"int\"]},{\"name\":\"status\",\"type\":[\"null\",\"string\"]}]}");
  @Deprecated public java.lang.CharSequence responding_product_id;
  @Deprecated public java.lang.CharSequence requesting_product_id;
  @Deprecated public java.lang.CharSequence module;
  @Deprecated public java.lang.CharSequence operation;
  @Deprecated public java.lang.CharSequence suboperation;
  @Deprecated public java.lang.CharSequence target_object_uri;
  @Deprecated public java.lang.Long object_size;
  @Deprecated public java.lang.Integer execution_time;
  @Deprecated public java.lang.CharSequence status;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return responding_product_id;
    case 1: return requesting_product_id;
    case 2: return module;
    case 3: return operation;
    case 4: return suboperation;
    case 5: return target_object_uri;
    case 6: return object_size;
    case 7: return execution_time;
    case 8: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: responding_product_id = (java.lang.CharSequence)value$; break;
    case 1: requesting_product_id = (java.lang.CharSequence)value$; break;
    case 2: module = (java.lang.CharSequence)value$; break;
    case 3: operation = (java.lang.CharSequence)value$; break;
    case 4: suboperation = (java.lang.CharSequence)value$; break;
    case 5: target_object_uri = (java.lang.CharSequence)value$; break;
    case 6: object_size = (java.lang.Long)value$; break;
    case 7: execution_time = (java.lang.Integer)value$; break;
    case 8: status = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'responding_product_id' field.
   */
  public java.lang.CharSequence getRespondingProductId() {
    return responding_product_id;
  }

  /**
   * Sets the value of the 'responding_product_id' field.
   * @param value the value to set.
   */
  public void setRespondingProductId(java.lang.CharSequence value) {
    this.responding_product_id = value;
  }

  /**
   * Gets the value of the 'requesting_product_id' field.
   */
  public java.lang.CharSequence getRequestingProductId() {
    return requesting_product_id;
  }

  /**
   * Sets the value of the 'requesting_product_id' field.
   * @param value the value to set.
   */
  public void setRequestingProductId(java.lang.CharSequence value) {
    this.requesting_product_id = value;
  }

  /**
   * Gets the value of the 'module' field.
   */
  public java.lang.CharSequence getModule() {
    return module;
  }

  /**
   * Sets the value of the 'module' field.
   * @param value the value to set.
   */
  public void setModule(java.lang.CharSequence value) {
    this.module = value;
  }

  /**
   * Gets the value of the 'operation' field.
   */
  public java.lang.CharSequence getOperation() {
    return operation;
  }

  /**
   * Sets the value of the 'operation' field.
   * @param value the value to set.
   */
  public void setOperation(java.lang.CharSequence value) {
    this.operation = value;
  }

  /**
   * Gets the value of the 'suboperation' field.
   */
  public java.lang.CharSequence getSuboperation() {
    return suboperation;
  }

  /**
   * Sets the value of the 'suboperation' field.
   * @param value the value to set.
   */
  public void setSuboperation(java.lang.CharSequence value) {
    this.suboperation = value;
  }

  /**
   * Gets the value of the 'target_object_uri' field.
   */
  public java.lang.CharSequence getTargetObjectUri() {
    return target_object_uri;
  }

  /**
   * Sets the value of the 'target_object_uri' field.
   * @param value the value to set.
   */
  public void setTargetObjectUri(java.lang.CharSequence value) {
    this.target_object_uri = value;
  }

  /**
   * Gets the value of the 'object_size' field.
   */
  public java.lang.Long getObjectSize() {
    return object_size;
  }

  /**
   * Sets the value of the 'object_size' field.
   * @param value the value to set.
   */
  public void setObjectSize(java.lang.Long value) {
    this.object_size = value;
  }

  /**
   * Gets the value of the 'execution_time' field.
   */
  public java.lang.Integer getExecutionTime() {
    return execution_time;
  }

  /**
   * Sets the value of the 'execution_time' field.
   * @param value the value to set.
   */
  public void setExecutionTime(java.lang.Integer value) {
    this.execution_time = value;
  }

  /**
   * Gets the value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /** Creates a new Call RecordBuilder */
  public static com.autodesk.ws.avro.Call.Builder newBuilder() {
    return new com.autodesk.ws.avro.Call.Builder();
  }
  
  /** Creates a new Call RecordBuilder by copying an existing Builder */
  public static com.autodesk.ws.avro.Call.Builder newBuilder(com.autodesk.ws.avro.Call.Builder other) {
    return new com.autodesk.ws.avro.Call.Builder(other);
  }
  
  /** Creates a new Call RecordBuilder by copying an existing Call instance */
  public static com.autodesk.ws.avro.Call.Builder newBuilder(com.autodesk.ws.avro.Call other) {
    return new com.autodesk.ws.avro.Call.Builder(other);
  }
  
  /**
   * RecordBuilder for Call instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Call>
    implements org.apache.avro.data.RecordBuilder<Call> {

    private java.lang.CharSequence responding_product_id;
    private java.lang.CharSequence requesting_product_id;
    private java.lang.CharSequence module;
    private java.lang.CharSequence operation;
    private java.lang.CharSequence suboperation;
    private java.lang.CharSequence target_object_uri;
    private java.lang.Long object_size;
    private java.lang.Integer execution_time;
    private java.lang.CharSequence status;

    /** Creates a new Builder */
    private Builder() {
      super(com.autodesk.ws.avro.Call.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.autodesk.ws.avro.Call.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Call instance */
    private Builder(com.autodesk.ws.avro.Call other) {
            super(com.autodesk.ws.avro.Call.SCHEMA$);
      if (isValidValue(fields()[0], other.responding_product_id)) {
        this.responding_product_id = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.responding_product_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.requesting_product_id)) {
        this.requesting_product_id = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.requesting_product_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.module)) {
        this.module = (java.lang.CharSequence) data().deepCopy(fields()[2].schema(), other.module);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.operation)) {
        this.operation = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.operation);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.suboperation)) {
        this.suboperation = (java.lang.CharSequence) data().deepCopy(fields()[4].schema(), other.suboperation);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.target_object_uri)) {
        this.target_object_uri = (java.lang.CharSequence) data().deepCopy(fields()[5].schema(), other.target_object_uri);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.object_size)) {
        this.object_size = (java.lang.Long) data().deepCopy(fields()[6].schema(), other.object_size);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.execution_time)) {
        this.execution_time = (java.lang.Integer) data().deepCopy(fields()[7].schema(), other.execution_time);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.status)) {
        this.status = (java.lang.CharSequence) data().deepCopy(fields()[8].schema(), other.status);
        fieldSetFlags()[8] = true;
      }
    }

    /** Gets the value of the 'responding_product_id' field */
    public java.lang.CharSequence getRespondingProductId() {
      return responding_product_id;
    }
    
    /** Sets the value of the 'responding_product_id' field */
    public com.autodesk.ws.avro.Call.Builder setRespondingProductId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.responding_product_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'responding_product_id' field has been set */
    public boolean hasRespondingProductId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'responding_product_id' field */
    public com.autodesk.ws.avro.Call.Builder clearRespondingProductId() {
      responding_product_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'requesting_product_id' field */
    public java.lang.CharSequence getRequestingProductId() {
      return requesting_product_id;
    }
    
    /** Sets the value of the 'requesting_product_id' field */
    public com.autodesk.ws.avro.Call.Builder setRequestingProductId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.requesting_product_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'requesting_product_id' field has been set */
    public boolean hasRequestingProductId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'requesting_product_id' field */
    public com.autodesk.ws.avro.Call.Builder clearRequestingProductId() {
      requesting_product_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'module' field */
    public java.lang.CharSequence getModule() {
      return module;
    }
    
    /** Sets the value of the 'module' field */
    public com.autodesk.ws.avro.Call.Builder setModule(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.module = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'module' field has been set */
    public boolean hasModule() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'module' field */
    public com.autodesk.ws.avro.Call.Builder clearModule() {
      module = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'operation' field */
    public java.lang.CharSequence getOperation() {
      return operation;
    }
    
    /** Sets the value of the 'operation' field */
    public com.autodesk.ws.avro.Call.Builder setOperation(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.operation = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'operation' field has been set */
    public boolean hasOperation() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'operation' field */
    public com.autodesk.ws.avro.Call.Builder clearOperation() {
      operation = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'suboperation' field */
    public java.lang.CharSequence getSuboperation() {
      return suboperation;
    }
    
    /** Sets the value of the 'suboperation' field */
    public com.autodesk.ws.avro.Call.Builder setSuboperation(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.suboperation = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'suboperation' field has been set */
    public boolean hasSuboperation() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'suboperation' field */
    public com.autodesk.ws.avro.Call.Builder clearSuboperation() {
      suboperation = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'target_object_uri' field */
    public java.lang.CharSequence getTargetObjectUri() {
      return target_object_uri;
    }
    
    /** Sets the value of the 'target_object_uri' field */
    public com.autodesk.ws.avro.Call.Builder setTargetObjectUri(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.target_object_uri = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'target_object_uri' field has been set */
    public boolean hasTargetObjectUri() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'target_object_uri' field */
    public com.autodesk.ws.avro.Call.Builder clearTargetObjectUri() {
      target_object_uri = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'object_size' field */
    public java.lang.Long getObjectSize() {
      return object_size;
    }
    
    /** Sets the value of the 'object_size' field */
    public com.autodesk.ws.avro.Call.Builder setObjectSize(java.lang.Long value) {
      validate(fields()[6], value);
      this.object_size = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'object_size' field has been set */
    public boolean hasObjectSize() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'object_size' field */
    public com.autodesk.ws.avro.Call.Builder clearObjectSize() {
      object_size = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'execution_time' field */
    public java.lang.Integer getExecutionTime() {
      return execution_time;
    }
    
    /** Sets the value of the 'execution_time' field */
    public com.autodesk.ws.avro.Call.Builder setExecutionTime(java.lang.Integer value) {
      validate(fields()[7], value);
      this.execution_time = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'execution_time' field has been set */
    public boolean hasExecutionTime() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'execution_time' field */
    public com.autodesk.ws.avro.Call.Builder clearExecutionTime() {
      execution_time = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'status' field */
    public java.lang.CharSequence getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public com.autodesk.ws.avro.Call.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.status = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'status' field */
    public com.autodesk.ws.avro.Call.Builder clearStatus() {
      status = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    public Call build() {
      try {
        Call record = new Call();
        record.responding_product_id = fieldSetFlags()[0] ? this.responding_product_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.requesting_product_id = fieldSetFlags()[1] ? this.requesting_product_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.module = fieldSetFlags()[2] ? this.module : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.operation = fieldSetFlags()[3] ? this.operation : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.suboperation = fieldSetFlags()[4] ? this.suboperation : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.target_object_uri = fieldSetFlags()[5] ? this.target_object_uri : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.object_size = fieldSetFlags()[6] ? this.object_size : (java.lang.Long) defaultValue(fields()[6]);
        record.execution_time = fieldSetFlags()[7] ? this.execution_time : (java.lang.Integer) defaultValue(fields()[7]);
        record.status = fieldSetFlags()[8] ? this.status : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
