/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.autodesk.ws.avro;  
@SuppressWarnings("all")
public enum InstanceType { 
  SESSION_START, SESSION_ATTRIBUTES, SESSION_END, CALL, SESSION_MAP, USER_MAP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"InstanceType\",\"namespace\":\"com.autodesk.ws.avro\",\"symbols\":[\"SESSION_START\",\"SESSION_ATTRIBUTES\",\"SESSION_END\",\"CALL\",\"SESSION_MAP\",\"USER_MAP\"]}");
}
