/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.autodesk.ws.avro;  
@SuppressWarnings("all")
public class NameValuePair extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NameValuePair\",\"namespace\":\"com.autodesk.ws.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"string\"}]}");
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence value;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /** Creates a new NameValuePair RecordBuilder */
  public static com.autodesk.ws.avro.NameValuePair.Builder newBuilder() {
    return new com.autodesk.ws.avro.NameValuePair.Builder();
  }
  
  /** Creates a new NameValuePair RecordBuilder by copying an existing Builder */
  public static com.autodesk.ws.avro.NameValuePair.Builder newBuilder(com.autodesk.ws.avro.NameValuePair.Builder other) {
    return new com.autodesk.ws.avro.NameValuePair.Builder(other);
  }
  
  /** Creates a new NameValuePair RecordBuilder by copying an existing NameValuePair instance */
  public static com.autodesk.ws.avro.NameValuePair.Builder newBuilder(com.autodesk.ws.avro.NameValuePair other) {
    return new com.autodesk.ws.avro.NameValuePair.Builder(other);
  }
  
  /**
   * RecordBuilder for NameValuePair instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NameValuePair>
    implements org.apache.avro.data.RecordBuilder<NameValuePair> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence value;

    /** Creates a new Builder */
    private Builder() {
      super(com.autodesk.ws.avro.NameValuePair.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.autodesk.ws.avro.NameValuePair.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing NameValuePair instance */
    private Builder(com.autodesk.ws.avro.NameValuePair other) {
            super(com.autodesk.ws.avro.NameValuePair.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.autodesk.ws.avro.NameValuePair.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.autodesk.ws.avro.NameValuePair.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'value' field */
    public java.lang.CharSequence getValue() {
      return value;
    }
    
    /** Sets the value of the 'value' field */
    public com.autodesk.ws.avro.NameValuePair.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'value' field has been set */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'value' field */
    public com.autodesk.ws.avro.NameValuePair.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public NameValuePair build() {
      try {
        NameValuePair record = new NameValuePair();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
