/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.autodesk.ws.avro;  
@SuppressWarnings("all")
public enum SessionType { 
  SESSION_DESKTOP, SESSION_OXYGEN, SESSION_MOBILE, SESSION_WEB  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SessionType\",\"namespace\":\"com.autodesk.ws.avro\",\"symbols\":[\"SESSION_DESKTOP\",\"SESSION_OXYGEN\",\"SESSION_MOBILE\",\"SESSION_WEB\"]}");
}
