/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.autodesk.ws.avro;  
@SuppressWarnings("all")
public class Session extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Session\",\"namespace\":\"com.autodesk.ws.avro\",\"fields\":[{\"name\":\"originating_product_id\",\"type\":\"string\"},{\"name\":\"session_type\",\"type\":{\"type\":\"enum\",\"name\":\"SessionType\",\"symbols\":[\"SESSION_DESKTOP\",\"SESSION_OXYGEN\",\"SESSION_MOBILE\",\"SESSION_WEB\"]}},{\"name\":\"user_id_type\",\"type\":{\"type\":\"enum\",\"name\":\"UserIdType\",\"symbols\":[\"USER_DESKTOP\",\"USER_OXYGEN\",\"USER_EIDM\",\"USER_MOBILE\",\"USER_WEB\"]}},{\"name\":\"originating_ip_address\",\"type\":[\"null\",\"string\"]}]}");
  @Deprecated public java.lang.CharSequence originating_product_id;
  @Deprecated public com.autodesk.ws.avro.SessionType session_type;
  @Deprecated public com.autodesk.ws.avro.UserIdType user_id_type;
  @Deprecated public java.lang.CharSequence originating_ip_address;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return originating_product_id;
    case 1: return session_type;
    case 2: return user_id_type;
    case 3: return originating_ip_address;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: originating_product_id = (java.lang.CharSequence)value$; break;
    case 1: session_type = (com.autodesk.ws.avro.SessionType)value$; break;
    case 2: user_id_type = (com.autodesk.ws.avro.UserIdType)value$; break;
    case 3: originating_ip_address = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'originating_product_id' field.
   */
  public java.lang.CharSequence getOriginatingProductId() {
    return originating_product_id;
  }

  /**
   * Sets the value of the 'originating_product_id' field.
   * @param value the value to set.
   */
  public void setOriginatingProductId(java.lang.CharSequence value) {
    this.originating_product_id = value;
  }

  /**
   * Gets the value of the 'session_type' field.
   */
  public com.autodesk.ws.avro.SessionType getSessionType() {
    return session_type;
  }

  /**
   * Sets the value of the 'session_type' field.
   * @param value the value to set.
   */
  public void setSessionType(com.autodesk.ws.avro.SessionType value) {
    this.session_type = value;
  }

  /**
   * Gets the value of the 'user_id_type' field.
   */
  public com.autodesk.ws.avro.UserIdType getUserIdType() {
    return user_id_type;
  }

  /**
   * Sets the value of the 'user_id_type' field.
   * @param value the value to set.
   */
  public void setUserIdType(com.autodesk.ws.avro.UserIdType value) {
    this.user_id_type = value;
  }

  /**
   * Gets the value of the 'originating_ip_address' field.
   */
  public java.lang.CharSequence getOriginatingIpAddress() {
    return originating_ip_address;
  }

  /**
   * Sets the value of the 'originating_ip_address' field.
   * @param value the value to set.
   */
  public void setOriginatingIpAddress(java.lang.CharSequence value) {
    this.originating_ip_address = value;
  }

  /** Creates a new Session RecordBuilder */
  public static com.autodesk.ws.avro.Session.Builder newBuilder() {
    return new com.autodesk.ws.avro.Session.Builder();
  }
  
  /** Creates a new Session RecordBuilder by copying an existing Builder */
  public static com.autodesk.ws.avro.Session.Builder newBuilder(com.autodesk.ws.avro.Session.Builder other) {
    return new com.autodesk.ws.avro.Session.Builder(other);
  }
  
  /** Creates a new Session RecordBuilder by copying an existing Session instance */
  public static com.autodesk.ws.avro.Session.Builder newBuilder(com.autodesk.ws.avro.Session other) {
    return new com.autodesk.ws.avro.Session.Builder(other);
  }
  
  /**
   * RecordBuilder for Session instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Session>
    implements org.apache.avro.data.RecordBuilder<Session> {

    private java.lang.CharSequence originating_product_id;
    private com.autodesk.ws.avro.SessionType session_type;
    private com.autodesk.ws.avro.UserIdType user_id_type;
    private java.lang.CharSequence originating_ip_address;

    /** Creates a new Builder */
    private Builder() {
      super(com.autodesk.ws.avro.Session.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.autodesk.ws.avro.Session.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Session instance */
    private Builder(com.autodesk.ws.avro.Session other) {
            super(com.autodesk.ws.avro.Session.SCHEMA$);
      if (isValidValue(fields()[0], other.originating_product_id)) {
        this.originating_product_id = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.originating_product_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.session_type)) {
        this.session_type = (com.autodesk.ws.avro.SessionType) data().deepCopy(fields()[1].schema(), other.session_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.user_id_type)) {
        this.user_id_type = (com.autodesk.ws.avro.UserIdType) data().deepCopy(fields()[2].schema(), other.user_id_type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.originating_ip_address)) {
        this.originating_ip_address = (java.lang.CharSequence) data().deepCopy(fields()[3].schema(), other.originating_ip_address);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'originating_product_id' field */
    public java.lang.CharSequence getOriginatingProductId() {
      return originating_product_id;
    }
    
    /** Sets the value of the 'originating_product_id' field */
    public com.autodesk.ws.avro.Session.Builder setOriginatingProductId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.originating_product_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'originating_product_id' field has been set */
    public boolean hasOriginatingProductId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'originating_product_id' field */
    public com.autodesk.ws.avro.Session.Builder clearOriginatingProductId() {
      originating_product_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'session_type' field */
    public com.autodesk.ws.avro.SessionType getSessionType() {
      return session_type;
    }
    
    /** Sets the value of the 'session_type' field */
    public com.autodesk.ws.avro.Session.Builder setSessionType(com.autodesk.ws.avro.SessionType value) {
      validate(fields()[1], value);
      this.session_type = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'session_type' field has been set */
    public boolean hasSessionType() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'session_type' field */
    public com.autodesk.ws.avro.Session.Builder clearSessionType() {
      session_type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'user_id_type' field */
    public com.autodesk.ws.avro.UserIdType getUserIdType() {
      return user_id_type;
    }
    
    /** Sets the value of the 'user_id_type' field */
    public com.autodesk.ws.avro.Session.Builder setUserIdType(com.autodesk.ws.avro.UserIdType value) {
      validate(fields()[2], value);
      this.user_id_type = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'user_id_type' field has been set */
    public boolean hasUserIdType() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'user_id_type' field */
    public com.autodesk.ws.avro.Session.Builder clearUserIdType() {
      user_id_type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'originating_ip_address' field */
    public java.lang.CharSequence getOriginatingIpAddress() {
      return originating_ip_address;
    }
    
    /** Sets the value of the 'originating_ip_address' field */
    public com.autodesk.ws.avro.Session.Builder setOriginatingIpAddress(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.originating_ip_address = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'originating_ip_address' field has been set */
    public boolean hasOriginatingIpAddress() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'originating_ip_address' field */
    public com.autodesk.ws.avro.Session.Builder clearOriginatingIpAddress() {
      originating_ip_address = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public Session build() {
      try {
        Session record = new Session();
        record.originating_product_id = fieldSetFlags()[0] ? this.originating_product_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.session_type = fieldSetFlags()[1] ? this.session_type : (com.autodesk.ws.avro.SessionType) defaultValue(fields()[1]);
        record.user_id_type = fieldSetFlags()[2] ? this.user_id_type : (com.autodesk.ws.avro.UserIdType) defaultValue(fields()[2]);
        record.originating_ip_address = fieldSetFlags()[3] ? this.originating_ip_address : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
