/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.autodesk.ws.avro;  
@SuppressWarnings("all")
public enum UserIdType { 
  USER_DESKTOP, USER_OXYGEN, USER_EIDM, USER_MOBILE, USER_WEB  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UserIdType\",\"namespace\":\"com.autodesk.ws.avro\",\"symbols\":[\"USER_DESKTOP\",\"USER_OXYGEN\",\"USER_EIDM\",\"USER_MOBILE\",\"USER_WEB\"]}");
}
